export const icons = {
    'doc': 'file-word-o',
    'docx': 'file-word-o',
    'pdf': 'file-pdf-o',
    'xls': 'file-excel',
    'xlsx': 'file-excel',
    'ppt': 'file-powerpoint',
    'pptx': 'file-powerpoint',
    'txt': 'file-alt',
    'html': 'file-code',
    'gif': 'file-photo-o',
    'png': 'file-photo-o',
    'jpg': 'file-photo-o',
    'jpeg': 'file-photo-o',
    'css': 'file-code',
    'js': 'file-code',
    'ts': 'file-code',
    'cs': 'file-code',
    'php': 'file-code',
    'json': 'file-code',
    'sql': 'file-code',
    'url': 'paperclip',
    'zip': 'file-zip-o',
};